# Generated by Django 5.0.2 on 2024-02-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('is_hq', models.BooleanField(default=False)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employer')),
            ],
        ),
    ]
