# Generated by Django 5.0.2 on 2024-02-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=1)),
                ('job_description', models.CharField(max_length=400)),
                ('qualifications', models.CharField(max_length=400)),
                ('benefits', models.CharField(max_length=400)),
                ('employment_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=12)),
                ('employment_arrangement', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=10)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employer')),
            ],
        ),
    ]
