# Generated by Django 5.0.2 on 2024-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='benefits',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='posting',
            name='employment_arrangement',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=10),
        ),
        migrations.AlterField(
            model_name='posting',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=12),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='posting',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='posting',
            name='max_salary',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='posting',
            name='min_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='posting',
            name='qualifications',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
