# Generated by Django 5.0.2 on 2024-02-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_posting_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='min_salary',
        ),
    ]
