# Generated by Django 5.0.2 on 2024-02-16 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_rename_user_id_user_id'),
        ('posting', '0003_remove_posting_max_salary_remove_posting_min_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employer')),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
            ],
        ),
    ]
